--- #YAML:1.0
name:                GRID-Machine
version:             0.107
abstract:            Remote Procedure Calls over a SSH link
license:             ~
author:              
    - Casiano Rodriguez-Leon <casiano@ull.es>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Module::Which:                 0.0205
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
